menu:
  - name: contact
    url: /contact/

social:
  - {icon: 'twitter', link: 'https://x.com/Dominic_willi_'}
  - {icon: 'linkedin', link: 'https://www.linkedin.com/in/dominic-williams-3a8489348'}
contacts:
  - {name: 'Williams Edidiong Dominic', title: 'Programme Officer', department: 'Governance Programmes', institution: 'Centre for Development Research Enlightenment and Advocacy (CDREA)', institution_address: 'Uyo, Akwa Ibom State, Nigeria', phone: '+234 708 612 8976', email: 'dominicwilliamad@gmail[dot]com', office: '', image: 'assets/img/contact.jpg'}